# Generated by Django 4.1.3 on 2023-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Price')),
                ('sku', models.CharField(blank=True, max_length=16, null=True, verbose_name='SKU')),
                ('currency', models.CharField(max_length=8, verbose_name='Currency')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('max_file_size', models.PositiveBigIntegerField(blank=True, default=209715200, null=True, verbose_name='Maximum file size')),
                ('storage_size', models.PositiveBigIntegerField(blank=True, default=2147483648, null=True, verbose_name='Storage size')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
