# Generated by Django 4.1.3 on 2023-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='psp_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='PSP ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='psp_reference',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='PSP ID'),
        ),
    ]
