# Generated by Django 4.1.3 on 2023-04-04 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('psp_id', models.CharField(max_length=64, verbose_name='PSP ID')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('object_name', models.CharField(max_length=16, verbose_name='Object name')),
                ('product_type', models.CharField(max_length=32, verbose_name='Product type')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp_id', models.CharField(max_length=64, verbose_name='PSP ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('current_period_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Current period end')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('billing_scheme', models.CharField(max_length=128, verbose_name='Billing scheme')),
                ('currency', models.CharField(max_length=8, verbose_name='Currency')),
                ('psp_id', models.CharField(max_length=64, verbose_name='PSP ID')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('object_name', models.CharField(max_length=16, verbose_name='Object name')),
                ('recurring', models.JSONField(blank=True, null=True, verbose_name='Recurring')),
                ('payment_type', models.CharField(max_length=32, verbose_name='Payment type')),
                ('unit_amount', models.PositiveIntegerField(verbose_name='Unit amount')),
                ('unit_amount_decimal', models.CharField(max_length=32, verbose_name='Unit amount decimal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payments.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp_id', models.CharField(max_length=64, verbose_name='PSP ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
