# Generated by Django 4.1.3 on 2023-04-24 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Current period end'),
        ),
    ]
