# Generated by Django 4.1.3 on 2022-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_file_size',
            field=models.IntegerField(blank=True, default=104857600, null=True, verbose_name='Maximum file size'),
        ),
    ]
