# Generated by Django 4.1.3 on 2023-02-10 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_max_file_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-id'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded date'),
        ),
    ]
