# Generated by Django 4.1.3 on 2023-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_file_options_file_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.CharField(editable=False, max_length=128, verbose_name='Content type'),
        ),
    ]
