# Generated by Django 4.1.3 on 2023-02-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.product'),
        ),
    ]
