# Generated by Django 4.1.3 on 2023-02-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_current_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Subscription',
        ),
    ]
