# Generated by Django 4.1.3 on 2023-03-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_current_product_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.subscription'),
        ),
    ]
