# Generated by Django 4.1.3 on 2023-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscription_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=128, verbose_name='Short description')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, default=104857600, null=True, verbose_name='Maximum file size'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='storage_size',
            field=models.PositiveBigIntegerField(blank=True, default=10737418240, null=True, verbose_name='Storage size'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='item_points',
            field=models.ManyToManyField(blank=True, to='accounts.productitempoint'),
        ),
    ]
