# Generated by Django 4.1.3 on 2023-03-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
        ('accounts', '0010_productitempoint_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='docs.termsofservice'),
        ),
    ]
