# Generated by Django 4.1.3 on 2023-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_terms_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_file_size',
            field=models.PositiveIntegerField(blank=True, default=209715200, null=True, verbose_name='Maximum file size'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='storage_size',
            field=models.PositiveBigIntegerField(blank=True, default=2147483648, null=True, verbose_name='Storage size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_file_size',
            field=models.IntegerField(blank=True, default=209715200, null=True, verbose_name='Maximum file size'),
        ),
    ]
