# Generated by Django 4.1.3 on 2023-03-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_subscription_item_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
