# Generated by Django 4.1.3 on 2023-03-02 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('reference', models.CharField(max_length=32, verbose_name='Reference')),
            ],
            options={
                'get_latest_by': ['date_created'],
            },
        ),
    ]
